spring.application.name=tamagoclub
# DataSource 
#Postgresのドライバー設定 
#spring.datasource.driver-class-name=org.postgresql.Driver 
#データベースへの接続URLを設定 
spring.datasource.url=
# データベース接続のためのユーザー名を設定 
spring.datasource.username=
#データベース接続のためのパスワードを設定 
spring.datasource.password=
# SQLスクリプトの初期化モード 
spring.sql.init.mode=always 
#ログ表示設定 
logging.level.com.example.demo.mapper=DEBUG
# MyBatis
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.example.demo.entity
#画像の最大サイズの設定 
spring.servlet.multipart.max-file-size=5MB 
spring.servlet.multipart.max-request-size=10MB
#スネークケースとキャメルケースの変換
mybatis.configuration.map-underscore-to-camel-case=true

spring.web.resources.cache.period=0
spring.web.resources.chain.cache=false
spring.web.resources.static-locations=file:src/main/resources/static/
